//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomType
    {
        public CustomType()
        {
            this.CustomerTables = new List<CustomerTable>();
        }
    
        public int Id_NewCustomerType { get; set; }
        public string CustomerType { get; set; }
    
        public virtual IList<CustomerTable> CustomerTables { get; set; }
    }
}
