//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace AdminRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KraticeTable
    {
        public int Id_K { get; set; }
        [Required(ErrorMessage = "Vnesite kratico!")]
        public string Kratica { get; set; }
        [Required(ErrorMessage = "Vnesite slo. opis!")]
        public string OpisSlo { get; set; }
        [Required(ErrorMessage = "Vnesite ang. opis!")]
        public string OpisAng { get; set; }
    }
}
