//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VlogaUporabnika
    {
        public VlogaUporabnika()
        {
            this.UsersTables = new List<UsersTable>();
        }
    
        public int Id_Vloga { get; set; }
        public string Naziv { get; set; }
    
        public virtual IList<UsersTable> UsersTables { get; set; }
    }
}
